-- site_manage
UPDATE `grid_basic_config` SET `sqlstr`='SELECT\n	tea.id as id,\n	tea.login_id as loginId,\n	tea.true_name as trueName,\n	pt.id as positionalTitleId,\n	pt.name as positionalTitle,\n	eb.id as eduBackgroundId,\n	eb.name as eduBackground,\n	tt.id as tutorTeacherId,\n	tt.name as tutorTeacher,\n	ct.id as courseTeacherId,\n	ct.name as courseTeacher,\n	ic.id as classMasterId,\n	ic.name as classMaster,\n	ac.id as activeId,\n	ac.name as activeName,\n	cat.id as cardTypeId,\n	cat.name as cardType,\n	tea.card_no as cardNo,\n	gen.id as genderId,\n	gen.name as gender,\n	tea.birthday as birthday,\n	tea.work_unit as workUnit,\n	tea.mobile as mobile,\n	tea.work_phone as workPhone,\n	tea.home_phone as homePhone,\n	tea.email as email,\n	tea.address as address,\n	tea.zip_code as zipCode,\n	tea.qq as qq,\n	if(wu.openid is null, \'否\', \'是\') as hasWeChat,\n	tea.introduction as introduction,\n        tea.picture_url as pictureUrl,\n        `is`.name as inSchool,\n        `is`.id as inSchoolId\nFROM\n	pe_teacher tea\nINNER JOIN enum_const pt ON pt.id = tea.flag_positional_title\nLEFT JOIN enum_const eb ON eb.id = tea.flag_educational_background\nINNER JOIN enum_const tt ON tt.id = tea.flag_tutor_teacher\nINNER JOIN enum_const ct ON ct.id = tea.flag_course_teacher\nINNER JOIN enum_const ic ON ic.id = tea.flag_isclassmaster\nINNER JOIN enum_const ac ON ac.id = tea.flag_active\nLEFT JOIN enum_const cat ON cat.id = tea.flag_card_type\nLEFT JOIN enum_const gen ON gen.id = tea.flag_gender\nLEFT JOIN wechat_user wu ON wu.fk_sso_user_id = tea.fk_sso_user_id\nLEFT JOIN enum_const `is` on `is`.id = tea.flag_in_school\nWHERE\n	tea.site_code = \'${siteCode}\'\ngroup BY\n	tea.id' WHERE (`id`='teacherResourceManage');
DELETE FROM grid_column_config WHERE id in ('4028ae316a1035ae016a103bebc90008','4028ae316a10bdef016a10c2c2140005');
UPDATE `grid_basic_config` SET `sqlstr`='SELECT\n  c.id AS id,\n  c. NAME AS name,\n  c. CODE AS code,\n  tt. NAME AS trainingTarget,\n  tt. id AS trainingTargetId,\n  ct. NAME AS courseType,\n  ct. id AS courseTypeId,\n  c.course_intro as courseIntro,\n  tea. NAME  AS teacherName,\n  tea.work_unit AS teaUnit,\n  tea.mobile as teaMobile,\n  tea.login_id as teaLoginId\nFROM\n	pe_course c\nleft JOIN enum_const tt ON tt.id = c.flag_training_target\nleft  JOIN enum_const ct ON ct.id = c.flag_course_type\nINNER JOIN pe_teacher tea ON tea.id = c.fk_teacher_id\nWHERE\n  c.site_code = \'${siteCode}\'' WHERE (`id`='courseResourceManage');
UPDATE `grid_column_config` SET `ID`='4028ae316af7d6ca016af7e41a9e0000', `fk_action_grid_config_id`='courseResourceManage', `name`='教师工作单位', `dataindex`='teaUnit', `data_column`='', `search`='1', `to_add`='0', `to_update`='0', `column_can_update`='0', `list`='1', `report`='1', `type`='TextField', `dateFormat`='yyyy-MM-dd', `allow_blank`='1', `max_length`='50', `check_message`='', `check_regular`='', `text_field_parameters`=NULL, `combo_sql`='', `serial_number`='8', `flag_active`='4028809c1d625bcf011d66fd0dda0006', `flag_bak`=NULL, `user_type`=NULL, `team`='', `s_note`='', `sql_result`='', `is_html`=NULL, `default_text`='', `cascade_columns`=NULL WHERE (`ID`='4028ae316af7d6ca016af7e41a9e0000');
-- 业务库
UPDATE pe_teacher tea
INNER JOIN pe_unit un ON un.id = tea.fk_unit_id
SET tea.work_unit=un.`name`
WHERE
	IFNULL(work_unit, '') = '';