SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE homework_member ADD FOREIGN KEY homework_member_sso_user_fk(fk_sso_user_id) REFERENCES sso_user(id);
ALTER TABLE homework_member ADD FOREIGN KEY homework_member_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_answer ADD FOREIGN KEY homework_answer_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_answer ADD FOREIGN KEY homework_answer_member_fk(fk_member_id) REFERENCES homework_member(id);
ALTER TABLE homework_answer_comment ADD FOREIGN KEY homework_answer_comment_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_answer_comment ADD FOREIGN KEY homework_answer_comment_answer_fk(fk_answer_id) REFERENCES homework_answer(id);
ALTER TABLE homework_answer_detail ADD FOREIGN KEY homework_answer_detail_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_answer_detail ADD FOREIGN KEY homework_answer_detail_answer_fk(fk_answer_id) REFERENCES homework_answer(id);
ALTER TABLE homework_group ADD FOREIGN KEY homework_group_course_fk(fk_course_id) REFERENCES pe_course(id);
ALTER TABLE homework_group ADD FOREIGN KEY homework_group_homework_type_fk(flag_homework_type) REFERENCES enum_const(id);
ALTER TABLE homework_group_detail ADD FOREIGN KEY homework_group_detail_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_group_photo MODIFY COLUMN fk_group_id varchar(50);
ALTER TABLE homework_group_photo ADD FOREIGN KEY homework_group_photo_group_fk(fk_group_id) REFERENCES homework_group(id);
ALTER TABLE homework_answer ADD INDEX homework_answer_score_index(score);
ALTER TABLE homework_answer ADD INDEX homework_answer_score_by_index(score_by);
ALTER TABLE homework_answer ADD INDEX homework_answer_is_delete_index(is_delete);
ALTER TABLE homework_answer_comment ADD INDEX homework_answer_comment_is_delete_index(is_delete);
ALTER TABLE homework_group ADD INDEX homework_group_item_id_index(item_id);
ALTER TABLE homework_group ADD INDEX homework_group_site_code_index(site_code);
ALTER TABLE homework_group ADD INDEX homework_group_is_delete_index(is_delete);
ALTER TABLE homework_member ADD INDEX homework_member_is_delete_index(is_delete);
ALTER TABLE pe_course ADD INDEX course_teacher_index(fk_teacher_id);
ALTER TABLE pe_student ADD FOREIGN KEY student_user_fk(fk_sso_user_id) REFERENCES sso_user(id);