-- 新增文件类型grid
INSERT INTO `grid_basic_config` (`id`, `title`, `can_search`, `can_add`, `can_delete`, `can_update`, `can_batch_add`, `can_projections`, `first_search`, `entity_class`, `note`, `list_type`, `dc`, `flag_active`, `flag_bak`, `dateFormat`, `sqlstr`, `statistics`, `s_note`, `update_note`, `is_enum`, `countsql`, `isGroupSql`, `LIST_FUNCTION`, `FLAG_INTE_ACTIVE`, `fk_web_site_id`, `can_checked_all`, `add_mode`, `add_cmp_name`, `fk_chart_id`) VALUES ('attachFileTypeManage', '附件类型管理', '1', NULL, NULL, NULL, NULL, '1', '0', 'com.whaty.core.framework.bean.EnumConst', NULL, '1', NULL, '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, 'SELECT\n	id AS id,\n	NAME AS name\nFROM\n	enum_const\nWHERE\n	namespace = \'flagAttachType\'\nAND team = \',${siteCode},\'', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, '4028ae316a09ee85016a09f4d7640000', '1', NULL, NULL, NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('063eb1bf15a011eabd12fcaa140ebf84', 'attachFileTypeManage', 'id', 'id', 'id', '0', '0', NULL, '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '0', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('063eb5c915a011eabd12fcaa140ebf84', 'attachFileTypeManage', '名称', 'name', 'name', '1', '1', NULL, '0', '1', '1', 'TextField', 'yyyy-MM-dd', '0', '50', '', '', NULL, '', '1', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30677', 'attachFileTypeManage', NULL, 'd54b3e85479a11e89697fcaa140ebf84', '添加', '', '', NULL, '0', '0', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30678', 'attachFileTypeManage', NULL, 'fc43396e479a11e89697fcaa140ebf84', '修改', '', '', NULL, '0', '0', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30679', 'attachFileTypeManage', NULL, '030ebfea479b11e89697fcaa140ebf84', '删除', '', '', NULL, '0', '0', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30680', 'attachFileTypeManage', NULL, 'f82ae75b479a11e89697fcaa140ebf84', '批量导入', '', '', NULL, '0', '0', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '4', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `pe_interface` (`id`, `name`, `url`, `method`, `flag_isvalid`) VALUES ('811', '附件类型', '/entity/basic/attachFileTypeManage/**', '', '2');
INSERT INTO `pe_base_category` (`id`, `name`, `code`, `router_name`, `url`, `fk_grid_id`, `flag_isvalid`, `flag_is_system`, `fk_base_category_group`) VALUES ('1265', '附件类型管理', '', '', '/entity/basic/attachFileTypeManage/abstractGrid', 'attachFileTypeManage', '2', '058cfaf74df211e8aac8fcaa140ebf84', '1');
INSERT INTO `pr_base_category_interface` (`id`, `fk_base_category_id`, `fk_interface_id`) VALUES ('919', '1265', '811');

-- 修改文件管理grid
UPDATE `grid_column_config` SET `ID`='4028ae316a48effb016a499d96460007', `fk_action_grid_config_id`='fileManage', `name`='类型', `dataindex`='combobox_enumConstByFlagAttachType.type', `data_column`='enumConstByFlagAttachType.name', `search`='1', `to_add`='0', `to_update`='1', `column_can_update`='0', `list`='1', `report`='1', `type`='TextField', `dateFormat`='yyyy-MM-dd', `allow_blank`='1', `max_length`='50', `check_message`='', `check_regular`='', `text_field_parameters`=NULL, `combo_sql`='SELECT id, name \nFROM enum_const \nWHERE namespace = \'flagAttachType\' AND team = \',${siteCode},\'', `serial_number`='2', `flag_active`='4028809c1d625bcf011d66fd0dda0006', `flag_bak`=NULL, `user_type`=NULL, `team`='', `s_note`='', `sql_result`='', `is_html`=NULL, `default_text`='', `cascade_columns`=NULL WHERE (`ID`='4028ae316a48effb016a499d96460007');
UPDATE `grid_menu_config` SET `id`='30684', `fk_grid_id`='fileManage', `flag_menu_type`=NULL, `flag_integrated_menu_type`='fc43396e479a11e89697fcaa140ebf84', `text`='修改', `show_type`='', `column_type`='', `fix`=NULL, `must_select_row`='0', `select_limit`='0', `data_index`='', `null_text`=NULL, `show_confirm`=NULL, `confirm_text`=NULL, `url`=NULL, `extra_parameters`=NULL, `waiting_msg`=NULL, `success_msg`=NULL, `error_msg`=NULL, `open_mode`=NULL, `form_config`=NULL, `user_type`=NULL, `flag_is_valid`='2', `serial_number`='2', `script`=NULL, `column_data_index`=NULL, `value`=NULL, `tips`=NULL, `extend_menu_config`=NULL WHERE (`id`='30684');
