SET FOREIGN_KEY_CHECKS=0;
delete from attach_file;
delete from attach_file_operate_record;
delete from check_flow;
delete from check_flow_auditor;
delete from check_flow_copy_person;
delete from check_flow_detail;
delete from check_flow_group;
delete from check_flow_node;
delete from check_flow_record;
delete from check_flow_type;
delete from class_course;
delete from class_course_timetable;
delete from class_hotel_arrange;
delete from class_hotel_detail;
delete from class_notice;
delete from class_online_exam;
delete from class_sign;
delete from class_sign_student;
delete from cooperate_unit;
delete from course_time;
delete from custom_analyse;
-- delete from custom_analyse_condition_config;
-- delete from custom_analyse_group;
-- delete from custom_analyse_item_config;
delete from custom_analyse_user_collection;
-- delete from custom_analyse_x_group_config;
-- delete from data_board;
delete from enroll_person;
delete from enroll_person_order_rel;
delete from enroll_user;
delete from enroll_user_collection;
delete from enroll_user_linkman;
delete from entrusted_unit;
delete from entrusted_unit_linkman;
-- delete from enum_const;
delete from exam_batch;
delete from exam_course;
delete from exam_reserve;
delete from exam_site;
delete from homework_answer;
delete from homework_answer_comment;
delete from homework_answer_detail;
delete from homework_group;
delete from homework_group_detail;
delete from homework_group_photo;
delete from homework_member;
delete from job_arrange;
delete from job_arrange_extend;
delete from live_course;
delete from operate_record;
delete from operate_status_record;
delete from operate_status_record_detail;
delete from order_invoice;
delete from overall_evaluate;
delete from overall_evaluate_answer;
delete from overall_evaluate_option;
delete from pe_area;
delete from pe_bulletin;
delete from pe_bulletin_class;
delete from pe_business_invoice;
delete from pe_business_order;
delete from pe_business_order_invoice;
delete from pe_business_unit;
-- delete from pe_chart_column_def;
-- delete from pe_chart_def;
delete from pe_class;
delete from pe_company;
delete from pe_course;
delete from pe_hotel;
delete from pe_manager;
delete from pe_notice;
delete from pe_order;
delete from pe_place;
delete from pe_pri_role;
delete from pe_print_template;
delete from pe_print_template_group;
delete from pe_print_template_sign;
delete from pe_printing;
delete from pe_received;
delete from pe_review;
delete from pe_review_opinion;
delete from pe_site_config;
delete from pe_student;
delete from pe_teacher;
delete from pe_unit;
delete from policy_regulation;
delete from policy_regulation_extend;
delete from pr_bulletin_user;
-- delete from pr_columns_config;
delete from pr_pri_manager_unit;
delete from pr_tch_stu_elective;
delete from pr_user_notice;
delete from prepare_item;
delete from pri_received_manager;
delete from pri_review_manager;
delete from printing_unit;
delete from questionnaire_answer;
delete from questionnaire_answer_detail;
delete from questionnaire_group;
delete from questionnaire_group_detail;
delete from questionnaire_group_photo;
delete from questionnaire_member;
delete from questionnaire_option;
delete from questionnaire_question;
delete from requirement_follow_up_info;
delete from requirement_info;
delete from send_message_analyse;
delete from send_message_history;
-- delete from send_message_time_config;
delete from shiro_permission;
delete from shiro_role;
delete from shiro_role_permission;
delete from shiro_user_role;
-- delete from sms_message_site;
-- delete from sms_template_config;
delete from sns_user_dynamic;
delete from sns_user_dynamic_comment;
delete from sns_user_dynamic_img;
delete from sso_user;
delete from sso_user_login;
delete from station_message;
delete from student_enroll_fee;
delete from student_enroll_fee_invoice;
delete from student_online_exam_score;
delete from student_online_exam_score_history;
-- delete from system_mylist_sql;
-- delete from system_variables;
delete from talk_group;
delete from talk_group_bulletin;
delete from talk_member;
delete from teacher_prepare_item;
delete from temporary_use_place;
delete from third_pay_data;
delete from training_certificate;
delete from training_item;
delete from training_item_apply;
delete from training_item_course;
delete from training_item_extend;
-- delete from upload_check_config;
-- delete from upload_check_item_config;
-- delete from upload_config;
delete from use_seal;
delete from user_advice;
delete from util_excel_table;
delete from wechat_access_token;
delete from wechat_app;
delete from wechat_app_user;
-- delete from wechat_basic;
delete from wechat_jsapi_ticket;
delete from wechat_receive_message;
-- delete from wechat_site;
delete from wechat_user;
delete from wechat_user_token