INSERT INTO `pe_base_category_group` (`id`, `name`, `code`) VALUES ('17', '待办催办', '17');

INSERT INTO `pe_base_category` (`id`, `name`, `code`, `router_name`, `url`, `fk_grid_id`, `flag_isvalid`, `flag_is_system`, `fk_base_category_group`) VALUES ('1399', '待办催办', 'training-task-manage', '', '/entity/task/trainingManagerTaskManage/abstractGrid', 'trainingManagerTaskManage', '2', '058cfaf74df211e8aac8fcaa140ebf84', '17');
INSERT INTO `pe_base_category` (`id`, `name`, `code`, `router_name`, `url`, `fk_grid_id`, `flag_isvalid`, `flag_is_system`, `fk_base_category_group`) VALUES ('1404', '任务列表', 'training-task-list', 'trainingTaskList', '', NULL, '2', '058cfaf74df211e8aac8fcaa140ebf84', '17');
INSERT INTO `pe_base_category` (`id`, `name`, `code`, `router_name`, `url`, `fk_grid_id`, `flag_isvalid`, `flag_is_system`, `fk_base_category_group`) VALUES ('1406', '任务详情', 'to-training-task-detail', 'toTrainingTaskDetail', '', NULL, '2', '058cfaf74df211e8aac8fcaa140ebf84', '17');

INSERT INTO `pe_interface` (`id`, `name`, `url`, `method`, `flag_isvalid`) VALUES ('922', '待办催办管理', '/entity/task/trainingManagerTaskManage/**', '', '2');
INSERT INTO `pe_interface` (`id`, `name`, `url`, `method`, `flag_isvalid`) VALUES ('927', '待办催办列表', '/entity/task/trainingManagerTaskList/**', '', '2');

INSERT INTO `pr_base_category_interface` (`fk_base_category_id`, `fk_interface_id`) VALUES ('1399', '922');
INSERT INTO `pr_base_category_interface` (`fk_base_category_id`, `fk_interface_id`) VALUES ('1404', '927');

INSERT INTO `grid_basic_config` (`id`, `title`, `can_search`, `can_add`, `can_delete`, `can_update`, `can_batch_add`, `can_projections`, `first_search`, `entity_class`, `note`, `list_type`, `dc`, `flag_active`, `flag_bak`, `dateFormat`, `sqlstr`, `statistics`, `s_note`, `update_note`, `is_enum`, `countsql`, `isGroupSql`, `LIST_FUNCTION`, `FLAG_INTE_ACTIVE`, `fk_web_site_id`, `can_checked_all`, `add_mode`, `add_cmp_name`, `fk_chart_id`) VALUES ('trainingManagerTaskManage', '待办催办', '1', NULL, NULL, NULL, NULL, '0', '0', 'com.whaty.domain.bean.TrainingManagerTask', NULL, '1', NULL, '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, 'SELECT\n  tmt.id as id,\n  tmt.name as name,\n  tt.name as taskType,\n  tt.id as taskTypeId,\n  tmt.charge_persons as chargePersonsId,\n  tmt.copy_persons as copyPersonsId,\n  tmt.start_time as startTime,\n  tmt.end_time as endTime,\n  GROUP_CONCAT(DISTINCT chr.name) as chargePersons,\n  GROUP_CONCAT(DISTINCT cop.name) as copyPersons,\n  pt.name as priorityLevel,\n  pt.id as priorityLevelId,\n  nw.name as notifyWay,\n  nw.id as notifyWayId,\n  tmt.note as note,\n  ttt.name as taskStatus,\n  ttt.id as taskStatusId,\n  cre.true_name as createManager\nFROM\n	training_manager_task tmt\nINNER JOIN enum_const tt on tt.id=tmt.flag_task_type\nINNER JOIN enum_const pt on pt.id=tmt.flag_priority_level\nleft JOIN enum_const ttt on ttt.id=tmt.flag_training_task_status\nINNER JOIN enum_const nw on nw.id=tmt.flag_notify_way\nINNER JOIN pe_manager chr on tmt.charge_persons like concat(\'%\',chr.id,\'%\')\nINNER JOIN pe_manager cop on tmt.copy_persons like concat(\'%\',cop.id,\'%\')\nINNER JOIN pe_manager cre on cre.id=tmt.create_manager\nINNER JOIN sso_user sso on sso.id=cre.fk_sso_user_id \nand sso.id=\'${currentUserId}\'\nwhere tmt.site_code=\'${siteCode}\'\nGROUP BY tmt.id', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, '4028ae316a09ee85016a09f4d7640000', '1', 'dialog', NULL, NULL);

INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f1a5ad20000', 'trainingManagerTaskManage', 'id', 'id', '', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '0', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f1af1820001', 'trainingManagerTaskManage', '名称', 'name', '', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '0', '50', '', '', NULL, '', '2', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f1c2f870002', 'trainingManagerTaskManage', '任务类型', 'combobox_enumConstByFlagTaskType.taskType', 'enumConstByFlagTaskType.name', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '0', '50', '', '', NULL, '', '1', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f2e628b0003', 'trainingManagerTaskManage', '考试时间', 'startTime', '', '1', '1', '1', '0', '1', '1', 'datetime', 'yyyy-MM-dd HH:mm:ss', '0', '50', '', '', NULL, '', '3', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f2ecca20004', 'trainingManagerTaskManage', '结束时间', 'endTime', '', '1', '1', '1', '0', '1', '1', 'datetime', 'yyyy-MM-dd HH:mm:ss', '0', '50', '', '', NULL, '', '4', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f3005fc0005', 'trainingManagerTaskManage', '负责人', 'chargePersons', '', '1', '0', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '5', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f3096790006', 'trainingManagerTaskManage', '抄送人', 'copyPersons', '', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '6', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f31bdf20007', 'trainingManagerTaskManage', '优先级', 'combobox_enumConstByFlagPriorityLevel.priorityLevel', 'enumConstByFlagPriorityLevel.name', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '0', '50', '', '', NULL, '', '7', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f32d5b60008', 'trainingManagerTaskManage', '通知方式', 'combobox_enumConstByFlagNotifyWay.notifyWay', 'enumConstByFlagNotifyWay.name', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '8', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f3371230009', 'trainingManagerTaskManage', '任务简介', 'note', '', '1', '1', '1', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '0', '50', '', '', NULL, '', '9', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f40ad53000a', 'trainingManagerTaskManage', 'taskTypeId', 'taskTypeId', 'enumConstByFlagTaskType.id', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '99', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f41e12c000b', 'trainingManagerTaskManage', 'priorityLevelId', 'priorityLevelId', 'enumConstByFlagPriorityLevel.id', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '99', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f432d9f000c', 'trainingManagerTaskManage', 'notifyWayId', 'notifyWayId', 'enumConstByFlagNotifyWay.id', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '99', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f7ef0a1016f7f8bdadd000e', 'trainingManagerTaskManage', '催办人', 'combobox_peManager.createManager', '', '1', '0', '0', '0', '1', '1', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '10', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f9c8158016f9d8237820003', 'trainingManagerTaskManage', 'chargePersonsId', 'chargePersonsId', '', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '99', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);
INSERT INTO `grid_column_config` (`ID`, `fk_action_grid_config_id`, `name`, `dataindex`, `data_column`, `search`, `to_add`, `to_update`, `column_can_update`, `list`, `report`, `type`, `dateFormat`, `allow_blank`, `max_length`, `check_message`, `check_regular`, `text_field_parameters`, `combo_sql`, `serial_number`, `flag_active`, `flag_bak`, `user_type`, `team`, `s_note`, `sql_result`, `is_html`, `default_text`, `cascade_columns`) VALUES ('4028aec76f9c8158016f9d828b7d0004', 'trainingManagerTaskManage', 'copyPersonsId', 'copyPersonsId', '', '0', '0', '0', '0', '0', '0', 'TextField', 'yyyy-MM-dd', '1', '50', '', '', NULL, '', '99', '4028809c1d625bcf011d66fd0dda0006', NULL, NULL, '', '', '', NULL, '', NULL);

INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30847', 'trainingManagerTaskManage', '524b30a5f93811e8a2c3fcaa140ebf84', NULL, '添加', 'top', 'left', '0', '0', '1', 'id', '', '1', '', NULL, NULL, '', NULL, NULL, '_blank', NULL, NULL, '2', '1', NULL, NULL, NULL, '', '{\"code\":\"add\"}');
INSERT INTO `grid_menu_config` (`id`, `fk_grid_id`, `flag_menu_type`, `flag_integrated_menu_type`, `text`, `show_type`, `column_type`, `fix`, `must_select_row`, `select_limit`, `data_index`, `null_text`, `show_confirm`, `confirm_text`, `url`, `extra_parameters`, `waiting_msg`, `success_msg`, `error_msg`, `open_mode`, `form_config`, `user_type`, `flag_is_valid`, `serial_number`, `script`, `column_data_index`, `value`, `tips`, `extend_menu_config`) VALUES ('30848', 'trainingManagerTaskManage', '524b30a5f93811e8a2c3fcaa140ebf84', NULL, '修改', 'top', 'left', '0', '1', '1', 'id', '', '1', '', NULL, NULL, '', NULL, NULL, '_blank', NULL, NULL, '2', '2', NULL, NULL, NULL, '', '{\"code\":\"edit\"}');

-- 复制菜单到其他站点
INSERT INTO `pe_pri_category` (
	`ID`,
	`NAME`,
	`FK_PARENT_ID`,
	`CODE`,
	`PATH`,
	`FLAG_LEFT_MENU`,
	`serial_Number`,
	`isActive`,
	`LEVEL`,
	`fk_grid_id`,
	`fk_web_site_id`,
	`icon`,
	`fk_base_category_id`,
	`base_id`,
	`show_in_left_menu`
)
SELECT
	REPLACE (uuid(), '-', ''),
	ppc.name,
	ppc.FK_PARENT_ID,
	ppc.code,
	ppc.PATH,
	ppc.FLAG_LEFT_MENU,
	ppc.serial_Number,
	ppc.isActive,
	ppc.LEVEL,
	ppc.fk_grid_id,
	ps.id,
	NULL,
	pbc.id,
	ppc.base_id,
	ppc.show_in_left_menu
FROM
	pe_web_site ps
INNER JOIN pe_web_site ps1 on ps1.code='training'
INNER JOIN pe_pri_category ppc on ppc.base_id in ('fea8a75f4f78499b9dbc330589f470ef',
'ce1301088e854dc9bc4ae2a3a585aeab',
'fb55baf31cf545d796ef02fdc090d9f1',
'e6436c372bcb4acdbb8d1c906f9a0e63')
AND ppc.fk_web_site_id=ps1.id
LEFT JOIN pe_base_category pbc on pbc.id=ppc.fk_base_category_id
WHERE
	ps.CODE not in ('training','control');